# Generated by Django 5.0.6 on 2024-07-03 09:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Truck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=False)),
                ('is_trash', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('location', models.CharField(max_length=255, null=True)),
                ('lat', models.FloatField(null=True)),
                ('lng', models.FloatField(null=True)),
                ('speed', models.IntegerField(null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=False)),
                ('is_trash', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('driverId', models.CharField(max_length=255, unique=True)),
                ('dutyStatus', models.CharField(choices=[('OFF', 'for off duty'), ('SB', 'for sleeper berth'), ('ON', 'for on duty not driving'), ('D', 'for driving'), ('YM', 'yard moves'), ('PC', 'authorized personal use of CMV')], max_length=3, null=True)),
                ('dutyStatusStartTime', models.DateTimeField(null=True)),
                ('shiftWorkMinutes', models.BigIntegerField()),
                ('shiftDriveMinutes', models.BigIntegerField()),
                ('cycleWorkMinutes', models.BigIntegerField()),
                ('maxShiftWorkMinutes', models.BigIntegerField()),
                ('maxShiftDriveMinutes', models.BigIntegerField()),
                ('maxCycleWorkMinutes', models.BigIntegerField()),
                ('homeTerminalTimeZoneWindows', models.CharField(max_length=255)),
                ('homeTerminalTimeZoneIana', models.CharField(max_length=255)),
                ('truckName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.truck', verbose_name='truck_details')),
            ],
            options={
                'db_table': 'drivers',
            },
        ),
    ]
